app/blueprints/user/__init__.py
from app.blueprints.user.views import user

app/blueprints/user/views.py
import logging
from celery import Celery
import requests
import json
from flask import Blueprint, render_template, request, redirect, current_app, url_for, flash

import app.engine.url_model
from app.engine.user_model import User
from app.engine.validators import *
from app_run import application
from app.creds.settings import CelerySettings

CELERY = Celery('celery_tasks',
                backend=CelerySettings.CELERY_BACKEND_URL,
                broker=CelerySettings.CELERY_BROKER_URL)

from flask_login import (
    current_user,
    login_required,
    login_user,
    logout_user,
)

from oauthlib.oauth2 import WebApplicationClient

user = Blueprint('user', __name__, template_folder='templates')

with application.app_context():
    GOOGLE_CLIENT_ID = current_app.config.get('GOOGLE_CLIENT_ID')
    GOOGLE_CLIENT_SECRET = current_app.config.get('GOOGLE_CLIENT_SECRET')
    client = WebApplicationClient(GOOGLE_CLIENT_ID)


def get_google_provider_cfg():
    with application.app_context():
        google_discovery_url = current_app.config.get('GOOGLE_DISCOVERY_URL')
    return requests.get(google_discovery_url).json()


@user.route('/home', methods=['GET', 'POST'])
@login_required
def home():
    short_url = None
    long_url = None
    new_url = True
    show_warning = False
    show_error = False
    cu = User(current_user.id)

    if not cu.is_authenticated:
        return redirect(url_for('page.index'))

    url_table_data = cu.get_top_user_urls()

    clicks_table_data = cu.get_most_clicked_urls()

    if request.method == 'POST':
        for key in request.form:
            logging.debug("Form keys:")
            logging.debug(key, request.form[key])

        long_url = request.form.get('longUrlInput')
        description = request.form.get('urlDescription', '')
        custom_suffix = request.form.get('customSuffix')
        days_to_live = request.form.get('urlDaysLive', None)

        logging.debug(long_url, description, custom_suffix, days_to_live)

        """
        Default behaviour is to assume that long url to be incorrect and show warning. Only if it passes validation, 
        proceeds to show short url.
        """
        show_warning = True

        days_to_live = validate_exp_date(days_to_live)

        custom_suffix = validate_suffix(custom_suffix)

        nu = app.engine.url_model.Url(current_user=cu, suffix=custom_suffix)
        logging.debug(nu.print_info())

        outcome_success = nu.create_url(long_url=long_url, description=description,
                                        days_to_live=days_to_live)
        logging.debug(nu.print_info())

        short_url = nu.short_url

        if outcome_success:
            new_url = False
            show_warning = False

    return render_template('home.html', short_url=short_url, long_url=long_url, url_table_data=url_table_data,
                           clicks_table_data=clicks_table_data,
                           new_url=new_url, show_warning=show_warning, show_error=show_error)


@user.route('/urls', methods=['GET', 'POST'])
@login_required
def urls():
    show_warning = False
    show_error = False
    cu = User(current_user.id)

    if request.method == 'POST':
        selected_sfxs = tuple(key for key in request.form)
        logging.debug(msg=f"{str(selected_sfxs)}, {str(len(selected_sfxs))}")
        if len(selected_sfxs) > 0:
            # send task to Celery
            args_to_send = (",".join("'" + x + "'" for x in selected_sfxs), current_user.id)
            logging.debug(args_to_send)
            del_task = CELERY.send_task('celery_tasks.delete_urls', args=args_to_send)
            while del_task.state == 'PENDING':
                logging.debug(del_task.state)
            logging.debug(del_task.state)

    all_url_table = cu.get_user_url_table()

    return render_template('urls.html', all_url_table=all_url_table, show_warning=show_warning, show_error=show_error)


@user.route('/settings', methods=['GET', 'POST'])
@login_required
def settings():
    return render_template('settings.html')


@user.route('/delete_account', methods=['GET', 'POST'])
@login_required
def delete_account():
    res = User(current_user.id).drop_user()
    if res is True:
        logout_user()
        flash('Your account was successfully deleted', 'success')
        return redirect(url_for('page.index'))
    else:
        logout_user()
        flash('Error! Try again later!', 'danger')
        return redirect(url_for('page.index'))


@user.route("/login")
def login():
    # Find out what URL to hit for Google login
    google_provider_cfg = get_google_provider_cfg()
    authorization_endpoint = google_provider_cfg["authorization_endpoint"]

    # Use library to construct the request for Google login and provide
    # scopes that let you retrieve user's profile from Google
    request_uri = client.prepare_request_uri(
        authorization_endpoint,
        redirect_uri=request.base_url + "/callback",
        scope=["openid", "email", "profile"],
    )
    return redirect(request_uri)


@user.route("/login/callback")
def callback():
    # Get authorization code Google sent back to you
    code = request.args.get("code")

    # Find out what URL to hit to get tokens that allow you to ask for
    # things on behalf of a user
    google_provider_cfg = get_google_provider_cfg()
    token_endpoint = google_provider_cfg["token_endpoint"]

    # Prepare and send a request to get tokens! Yay tokens!
    token_url, headers, body = client.prepare_token_request(
        token_endpoint,
        authorization_response=request.url,
        redirect_url=request.base_url,
        code=code
    )
    token_response = requests.post(
        token_url,
        headers=headers,
        data=body,
        auth=(GOOGLE_CLIENT_ID, GOOGLE_CLIENT_SECRET),
    )

    # Parse the tokens!
    client.parse_request_body_response(json.dumps(token_response.json()))

    # Now that you have tokens (yay) let's find and hit the URL
    # from Google that gives you the user's profile information,
    # including their Google profile image and email
    userinfo_endpoint = google_provider_cfg["userinfo_endpoint"]
    uri, headers, body = client.add_token(userinfo_endpoint)
    userinfo_response = requests.get(uri, headers=headers, data=body)

    # You want to make sure their email is verified.
    # The user authenticated with Google, authorized your
    # app, and now you've verified their email through Google!
    if userinfo_response.json().get("email_verified"):
        unique_id = userinfo_response.json()["sub"]
        users_email = userinfo_response.json()["email"]
        picture = userinfo_response.json()["picture"]
        users_name = userinfo_response.json()["given_name"]
    else:
        return "User email not available or not verified by Google.", 400

    # Create a user in your db with the information provided
    # by Google
    google_user = User(
        id_=unique_id, name=users_name, email=users_email, profile_pic=picture
    )

    # Doesn't exist? Add it to the database.
    if not User(unique_id).get():
        u = User(unique_id, users_name, users_email, picture)
        u.create()
        return redirect(url_for("page.signup"))

    # Begin user session by logging the user in
    login_user(google_user)

    # Send user back to homepage
    return redirect(url_for("user.home"))


@user.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for("page.index"))

app/blueprints/user/templates/home.html
{% extends "base.html" %}
{%- from "layout-header.html" import layout_header -%}
{%- from "footer-layout.html" import footer_layout -%}
{%- from "user_url_forms.html" import new_url_form, ready_url_form -%}
{%- from "ready-index-layout.html" import ready_index_layout -%}
{%- from "tables.html" import basic_table -%}
{% set is_authenticated = current_user.is_authenticated%}
{% block content%}

<!-- adding headers -->
{{ layout_header(is_authenticated=is_authenticated) }}

<!-- setting urls  -->
{% if long_url %}
{% set url_place_holder = long_url %}
{% else %}
{% set url_place_holder = "Enter an URL to shorten" %}
{% endif %}

<div class="container-fluid" id="main">

    <div class="row" id="quickUrl">

        <div class="col-xs-auto col-sm-2 col-md-3 col-lg-3 col-xl-3">
        </div>
        <!--end empty col  -->
        <div class="col-xs-12 col-sm-8 col-md-6 col-lg-6 col-xl-6">
            <!--start url form            -->
            {% if new_url %}
            <div class="card" id="descTextTop">
            <div class="card-header h3">Add a new short URL</div>
            <div class="card-body">
              <p class="card-text">{{ new_url_form(show_warning=show_warning) }}</p>
            </div>
            </div>
            {% else %}
            {{ ready_index_layout(long_url=long_url, short_url=short_url, url_place_holder=url_place_holder) }}
            {% endif %}
            <!--            end url form-->
            {% if url_table_data.data|length > 0%}
            <div class="card" id="recentUrlTablesDesc">
            <div class="card-header h3">
                Your latest links
            </div>
            <!--                end card header-->
            <div class="card-body">
                {{ basic_table(headers=url_table_data.headers, data=url_table_data.data, id='recentUrlTable') }}
            </div>
            <!--    end card-body-->
            </div>
            {% endif %}
            <!--            end card-->
            <div><p></p></div>
            {% if clicks_table_data.data|length > 0%}
            <div class="card" id="topUrlTablesDesc">
            <div class="card-header h3">
                Top 10 links by clicks
            </div>
            <!--                end card-header-->

            <div class="card-body">
              {{ basic_table(headers=clicks_table_data.headers, data=clicks_table_data.data, id='topUrlTable') }}
            </div>
            <!--                end card-body-->
            </div>
            <!--            end card-->
            {% endif %}
        </div>
        <!-- end col-->
        <div class="col-xs-auto col-sm-2 col-md-3 col-lg-3 col-xl-3">
        </div>
        <!--end empty col  -->
    </div>
    <!-- end row quickUrl -->

</div>
<!-- end main container -->
{% endblock%}

<!-- adding footers -->
{{ footer_layout() }}

app/blueprints/user/templates/settings.html
{% extends "base.html" %}
{%- from "layout-header.html" import layout_header -%}
{%- from "footer-layout.html" import footer_layout -%}
{%- from "ready-index-layout.html" import ready_index_layout -%}
{%- from "default-index-layout.html" import default_index_layout -%}
{% set is_authenticated = current_user.is_authenticated%}
{% block content%}

<!-- adding headers -->
{{ layout_header(is_authenticated=is_authenticated) }}

<!-- setting urls  -->

<div class="container-fluid" id="main">

    <div class="row" id="quickUrl">

<!--        <div class="col-xs-auto col-sm-3 col-md-3 col-lg-3 col-xl-3">-->
<!--            &lt;!&ndash; empty column &ndash;&gt;-->
<!--        </div>-->

        <div class=" col-xs-12 col-sm-9 col-md-6 col-lg-6 col-xl-6">
            <h6>Account settings and management</h6>
            <button type="button" class="btn btn-link" data-toggle="modal" data-target="#deleteModal">
                Delete account
            </button>
            <!--      <a href="#" class="btn btn-link" role="button">Delete account</a>-->

            <!-- The Delete Modal -->
            <div class="modal fade" id="deleteModal">
                <div class="modal-dialog modal-lg">
                    <div class="modal-content">

                        <!-- Modal Header -->
                        <div class="modal-header">
                            <h4 class="modal-title">You cannot undo this action!</h4>
                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                        </div>

                        <!-- Modal body -->
                        <div class="modal-body">
                            All data about your links and statistics will be lost!
                        </div>

                        <!-- Modal footer -->
                        <div class="modal-footer">
                            <a href="{{url_for('user.delete_account')}}" class="btn btn-danger" role="button">Delete</a>
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                        </div>

                    </div>
                </div>
            </div>

        </div>
        <!-- end col-->

<!--        <div class="col-xs-auto col-sm-auto col-md-3 col-lg-3 col-xl-3">-->
<!--            &lt;!&ndash; empty column &ndash;&gt;-->
<!--        </div>-->
    </div>
    <!-- end row quickUrl -->

</div>
<!-- end main container -->
{% endblock%}

<!-- adding footers -->
{{ footer_layout() }}

app/blueprints/user/templates/urls.html
{% extends "base.html" %}
{%- from "layout-header.html" import layout_header -%}
{%- from "footer-layout.html" import footer_layout -%}
{%- from "ready-index-layout.html" import ready_index_layout -%}
{%- from "default-index-layout.html" import default_index_layout -%}
{% set is_authenticated = current_user.is_authenticated%}
{%- from "tables.html" import urls_table -%}
{% block content%}

<!-- adding headers -->
{{ layout_header(is_authenticated=is_authenticated) }}

<!-- setting urls  -->

<div class="container-fluid" id="main">

  <div class="row" id="quickUrl">

<!--    <div class="col-xs-auto col-sm-3 col-md-3 col-lg-3 col-xl-3" >-->
<!--      &lt;!&ndash; empty column &ndash;&gt;-->
<!--    </div>-->
      
    <div class="col-xs-12 col-lg-9" >
      {% if all_url_table.data|length > 0%}
            <div class="card" id="recentUrlTablesDesc">
            <div class="card-header h3">
                Your URLs
            </div>
            <!--                end card header-->
            <div class="card-body">
                {{ urls_table(headers=all_url_table.headers, data=all_url_table.data, id='allUrlTable') }}
            </div>
            <!--    end card-body-->
            </div>
      {% endif %}
            <!--            end card-->
    </div>
      <!-- end col-->

<!--      <div class="col-xs-auto col-sm-auto col-md-3 col-lg-3 col-xl-3" >-->
<!--        &lt;!&ndash; empty column &ndash;&gt;-->
<!--      </div>-->
  </div>
  <!-- end row quickUrl -->

</div>
<!-- end main container -->
{% endblock%}

<!-- adding footers -->
{{ footer_layout() }}