app/blueprints/page/__init__.py
from app.blueprints.page.views import page

app/blueprints/page/views.py
import logging

from flask import Blueprint, render_template, request, redirect, url_for

import app.engine.url_model
from app.db.db_procs import log_click
from app.etl.tracker import get_user_info
from app.creds.settings import OwnUrls

page = Blueprint('page', __name__, template_folder='templates')

from flask_login import (
    current_user,
)


@page.route('/', methods=['GET', 'POST'])
def index():
    if current_user.is_authenticated:
        return redirect(url_for('user.home'))

    short_url = None
    long_url = None
    new_url = True
    show_warning = False
    show_error = False

    if request.method == 'POST':
        long_url = request.form['longUrlInput']
        print(long_url)
        """
        Default behaviour is to assume that long url to be incorrect and show warning. Only if it passes validation, 
        proceeds to show short url.
        """
        show_warning = True

        nu = app.engine.url_model.Url()
        outcome_success = nu.create_url(long_url)
        short_url = nu.short_url
        if outcome_success:
            new_url = False
            show_warning = False

    return render_template('index.html', short_url=short_url, long_url=long_url,
                           new_url=new_url, show_warning=show_warning, show_error=show_error, is_auth=False)


@page.route('/signup')
def signup():
    return render_template('signup.html')


@page.route('/about')
def about():
    return render_template('about.html')


@page.route('/terms')
def terms():
    return render_template('terms.html')


@page.route('/privacy')
def privacy():
    return render_template('privacy.html')


@page.route('/<string:suffix>', methods=['GET'])
def url_redirect(suffix):

    long_url = app.engine.url_model.Url().match_long_url(suffix)

    print(long_url)
    if long_url == '404':
        return redirect(url_for('page.not_found'))

    if long_url:
        click_source = get_user_info()
        log_click(suffix, click_source)
        return redirect(long_url, code=302)

    return render_template('index.html', short_url=None, long_url=None, new_url=True, show_error=True)


@page.route('/not_found', methods=['GET'])
def not_found():
    return render_template('404.html', code=404)

app/blueprints/page/templates/about.html
{% extends "base.html" %}
{%- from "layout-header.html" import layout_header -%}
{%- from "footer-layout.html" import footer_layout -%}
{% set is_authenticated = current_user.is_authenticated%}
{% block content %}

<!-- adding headers -->
{{ layout_header(is_authenticated=is_authenticated) }}
<p>

</p>
<div class="container-fluid" id="main">
    <div class="row" id="descRow">

        <div class="col-xs-auto col-sm-2 col-md-3 col-lg-3 col-xl-3">

        </div>

        <div class="col-xs-12 col-sm-8 col-md-6 col-lg-6 col-xl-6">
            <div class="card" id="descTextEnd">
                <div class="card-header h2">
                    About page
                </div>
                <div class="card-body">
                    <p class="card-text">
                        Some benefits are on the surface: you can share shorter, nicer links. But also you can manage
                        availability of the links, control a link lifecycle, see statistics of clicks, etc.
                    </p>
                </div>
            </div>
        </div>

        <div class="col-xs-auto col-sm-2 col-md-3 col-lg-3 col-xl-3">

        </div>
    </div>
</div>
<!-- end main container -->
{% endblock %}

<!-- adding footers -->
{{ footer_layout() }}

app/blueprints/page/templates/index.html
{% extends "base.html" %}
{%- from "layout-header.html" import layout_header -%}
{%- from "footer-layout.html" import footer_layout -%}
{% set is_authenticated = current_user.is_authenticated%}
{% block content %}

<!-- adding headers -->
{{ layout_header(is_authenticated=is_authenticated) }}
<p>

</p>
<div class="container-fluid" id="main">
    <div class="row" id="descRow">

        <div class="col-xs-auto col-sm-2 col-md-3 col-lg-3 col-xl-3">

        </div>

        <div class="col-xs-12 col-sm-8 col-md-6 col-lg-6 col-xl-6">
            <div class="card" id="descTextEnd">
                <div class="card-header h2">
                    Why to use free and fast url shortener?
                </div>
                <div class="card-body">
                    <p class="card-text">
                        Some benefits are on the surface: you can share shorter, nicer links. But also you can manage
                        availability of the links, control a link lifecycle, see statistics of clicks, etc.
                    </p>
                    <p></p>
                    <div class="btn-group">
                        <a href="{{url_for('page.signup')}}" class="btn btn-primary" role="button" style="width: 150px;">SIGN UP</a>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-xs-auto col-sm-2 col-md-3 col-lg-3 col-xl-3">

        </div>
    </div>
</div>
<!-- end main container -->
{% endblock %}

<!-- adding footers -->
{{ footer_layout() }}

app/blueprints/page/templates/privacy.html
{% extends "base.html" %}
{%- from "layout-header.html" import layout_header -%}
{%- from "footer-layout.html" import footer_layout -%}
{% set is_authenticated = current_user.is_authenticated%}
{% block content %}

<!-- adding headers -->
{{ layout_header(is_authenticated=is_authenticated) }}
<p>

</p>
<div class="container-fluid" id="main">
    <div class="row" id="descRow">

        <div class="col-xs-auto col-sm-2 col-md-3 col-lg-3 col-xl-3">

        </div>

        <div class="col-xs-12 col-sm-8 col-md-6 col-lg-6 col-xl-6">
            <div class="card" id="descTextEnd">
                <div class="card-header h2">
                    Privacy page
                </div>
                <div class="card-body">
                    <p class="card-text">
                        Some benefits are on the surface: you can share shorter, nicer links. But also you can manage
                        availability of the links, control a link lifecycle, see statistics of clicks, etc.
                    </p>
                </div>
            </div>
        </div>

        <div class="col-xs-auto col-sm-2 col-md-3 col-lg-3 col-xl-3">

        </div>
    </div>
</div>
<!-- end main container -->
{% endblock %}

<!-- adding footers -->
{{ footer_layout() }}

app/blueprints/page/templates/signup.html
{% extends "base.html" %}
{%- from "layout-header.html" import layout_header -%}
{%- from "footer-layout.html" import footer_layout -%}
{% block content%}

<!-- adding headers -->
{{ layout_header() }}



<div class="container-fluid" id="main">

  <div class="row" id="quickUrl">

    <div class="col-xs-auto col-sm-3 col-md-3 col-lg-3 col-xl-3" >
      <!-- empty column -->
    </div>
      
    <div class=" col-xs-12 col-sm-9 col-md-6 col-lg-6 col-xl-6" >
      <div>
        <p></p>
      </div>  
      <div class="card" id="mainText">
        <div class="card-body">
          <p class="card-text">
            By clicking the button you confirm that you are agree with terms of use and privacy.
          </p>
          <a href="{{url_for('user.login')}}" class="btn btn-primary">Sign Up</a>
        </div>
      </div>
      <!-- end end text card -->

      </div>
      <!-- end col-->

      <div class="col-xs-auto col-sm-auto col-md-3 col-lg-3 col-xl-3" >
        <!-- empty column -->
      </div>
  </div>
  <!-- end quickUrl -->

</div>
<!-- end main container -->
{% endblock%}

<!-- adding footers -->
{{ footer_layout() }}

app/blueprints/page/templates/terms.html
{% extends "base.html" %}
{%- from "layout-header.html" import layout_header -%}
{%- from "footer-layout.html" import footer_layout -%}
{% set is_authenticated = current_user.is_authenticated%}
{% block content %}

<!-- adding headers -->
{{ layout_header(is_authenticated=is_authenticated) }}
<p>

</p>
<div class="container-fluid" id="main">
    <div class="row" id="descRow">

        <div class="col-xs-auto col-sm-2 col-md-3 col-lg-3 col-xl-3">

        </div>

        <div class="col-xs-12 col-sm-8 col-md-6 col-lg-6 col-xl-6">
            <div class="card" id="descTextEnd">
                <div class="card-header h2">
                    Terms of use
                </div>
                <div class="card-body">
                    <p class="card-text">
                        Some benefits are on the surface: you can share shorter, nicer links. But also you can manage
                        availability of the links, control a link lifecycle, see statistics of clicks, etc.
                    </p>
                </div>
            </div>
        </div>

        <div class="col-xs-auto col-sm-2 col-md-3 col-lg-3 col-xl-3">

        </div>
    </div>
</div>
<!-- end main container -->
{% endblock %}

<!-- adding footers -->
{{ footer_layout() }}