app/blueprints/page/views.py
import logging

from flask import Blueprint, render_template, request, redirect, url_for

import app.engine.url_model
from app.db.db_procs import log_click
from app.etl.tracker import get_user_info
from app.creds.settings import OwnUrls

page = Blueprint('page', __name__, template_folder='templates')

from flask_login import (
    current_user,
)


@page.route('/', methods=['GET', 'POST'])
def index():
    if current_user.is_authenticated:
        return redirect(url_for('user.home'))

    short_url = None
    long_url = None
    new_url = True
    show_warning = False
    show_error = False

    if request.method == 'POST':
        long_url = request.form['longUrlInput']
        print(long_url)
        """
        Default behaviour is to assume that long url to be incorrect and show warning. Only if it passes validation, 
        proceeds to show short url.
        """
        show_warning = True

        nu = app.engine.url_model.Url()
        outcome_success = nu.create_url(long_url)
        short_url = nu.short_url
        if outcome_success:
            new_url = False
            show_warning = False

    return render_template('index.html', short_url=short_url, long_url=long_url,
                           new_url=new_url, show_warning=show_warning, show_error=show_error, is_auth=False)


@page.route('/signup')
def signup():
    return render_template('signup.html')


@page.route('/about')
def about():
    return render_template('about.html')


@page.route('/terms')
def terms():
    return render_template('terms.html')


@page.route('/privacy')
def privacy():
    return render_template('privacy.html')


@page.route('/<string:suffix>', methods=['GET'])
def url_redirect(suffix):

    long_url = app.engine.url_model.Url().match_long_url(suffix)

    print(long_url)
    if long_url == '404':
        return redirect(url_for('page.not_found'))

    if long_url:
        click_source = get_user_info()
        log_click(suffix, click_source)
        return redirect(long_url, code=302)

    return render_template('index.html', short_url=None, long_url=None, new_url=True, show_error=True)


@page.route('/not_found', methods=['GET'])
def not_found():
    return render_template('404.html', code=404)

app/blueprints/user/views.py
import logging
from celery import Celery
import requests
import json
from flask import Blueprint, render_template, request, redirect, current_app, url_for, flash

import app.engine.url_model
from app.engine.user_model import User
from app.engine.validators import *
from app_run import application
from app.creds.settings import CelerySettings

CELERY = Celery('celery_tasks',
                backend=CelerySettings.CELERY_BACKEND_URL,
                broker=CelerySettings.CELERY_BROKER_URL)

from flask_login import (
    current_user,
    login_required,
    login_user,
    logout_user,
)

from oauthlib.oauth2 import WebApplicationClient

user = Blueprint('user', __name__, template_folder='templates')

with application.app_context():
    GOOGLE_CLIENT_ID = current_app.config.get('GOOGLE_CLIENT_ID')
    GOOGLE_CLIENT_SECRET = current_app.config.get('GOOGLE_CLIENT_SECRET')
    client = WebApplicationClient(GOOGLE_CLIENT_ID)


def get_google_provider_cfg():
    with application.app_context():
        google_discovery_url = current_app.config.get('GOOGLE_DISCOVERY_URL')
    return requests.get(google_discovery_url).json()


@user.route('/home', methods=['GET', 'POST'])
@login_required
def home():
    short_url = None
    long_url = None
    new_url = True
    show_warning = False
    show_error = False
    cu = User(current_user.id)

    if not cu.is_authenticated:
        return redirect(url_for('page.index'))

    url_table_data = cu.get_top_user_urls()

    clicks_table_data = cu.get_most_clicked_urls()

    if request.method == 'POST':
        for key in request.form:
            logging.debug("Form keys:")
            logging.debug(key, request.form[key])

        long_url = request.form.get('longUrlInput')
        description = request.form.get('urlDescription', '')
        custom_suffix = request.form.get('customSuffix')
        days_to_live = request.form.get('urlDaysLive', None)

        logging.debug(long_url, description, custom_suffix, days_to_live)

        """
        Default behaviour is to assume that long url to be incorrect and show warning. Only if it passes validation, 
        proceeds to show short url.
        """
        show_warning = True

        days_to_live = validate_exp_date(days_to_live)

        custom_suffix = validate_suffix(custom_suffix)

        nu = app.engine.url_model.Url(current_user=cu, suffix=custom_suffix)
        logging.debug(nu.print_info())

        outcome_success = nu.create_url(long_url=long_url, description=description,
                                        days_to_live=days_to_live)
        logging.debug(nu.print_info())

        short_url = nu.short_url

        if outcome_success:
            new_url = False
            show_warning = False

    return render_template('home.html', short_url=short_url, long_url=long_url, url_table_data=url_table_data,
                           clicks_table_data=clicks_table_data,
                           new_url=new_url, show_warning=show_warning, show_error=show_error)


@user.route('/urls', methods=['GET', 'POST'])
@login_required
def urls():
    show_warning = False
    show_error = False
    cu = User(current_user.id)

    if request.method == 'POST':
        selected_sfxs = tuple(key for key in request.form)
        logging.debug(msg=f"{str(selected_sfxs)}, {str(len(selected_sfxs))}")
        if len(selected_sfxs) > 0:
            # send task to Celery
            args_to_send = (",".join("'" + x + "'" for x in selected_sfxs), current_user.id)
            logging.debug(args_to_send)
            del_task = CELERY.send_task('celery_tasks.delete_urls', args=args_to_send)
            while del_task.state == 'PENDING':
                logging.debug(del_task.state)
            logging.debug(del_task.state)

    all_url_table = cu.get_user_url_table()

    return render_template('urls.html', all_url_table=all_url_table, show_warning=show_warning, show_error=show_error)


@user.route('/settings', methods=['GET', 'POST'])
@login_required
def settings():
    return render_template('settings.html')


@user.route('/delete_account', methods=['GET', 'POST'])
@login_required
def delete_account():
    res = User(current_user.id).drop_user()
    if res is True:
        logout_user()
        flash('Your account was successfully deleted', 'success')
        return redirect(url_for('page.index'))
    else:
        logout_user()
        flash('Error! Try again later!', 'danger')
        return redirect(url_for('page.index'))


@user.route("/login")
def login():
    # Find out what URL to hit for Google login
    google_provider_cfg = get_google_provider_cfg()
    authorization_endpoint = google_provider_cfg["authorization_endpoint"]

    # Use library to construct the request for Google login and provide
    # scopes that let you retrieve user's profile from Google
    request_uri = client.prepare_request_uri(
        authorization_endpoint,
        redirect_uri=request.base_url + "/callback",
        scope=["openid", "email", "profile"],
    )
    return redirect(request_uri)


@user.route("/login/callback")
def callback():
    # Get authorization code Google sent back to you
    code = request.args.get("code")

    # Find out what URL to hit to get tokens that allow you to ask for
    # things on behalf of a user
    google_provider_cfg = get_google_provider_cfg()
    token_endpoint = google_provider_cfg["token_endpoint"]

    # Prepare and send a request to get tokens! Yay tokens!
    token_url, headers, body = client.prepare_token_request(
        token_endpoint,
        authorization_response=request.url,
        redirect_url=request.base_url,
        code=code
    )
    token_response = requests.post(
        token_url,
        headers=headers,
        data=body,
        auth=(GOOGLE_CLIENT_ID, GOOGLE_CLIENT_SECRET),
    )

    # Parse the tokens!
    client.parse_request_body_response(json.dumps(token_response.json()))

    # Now that you have tokens (yay) let's find and hit the URL
    # from Google that gives you the user's profile information,
    # including their Google profile image and email
    userinfo_endpoint = google_provider_cfg["userinfo_endpoint"]
    uri, headers, body = client.add_token(userinfo_endpoint)
    userinfo_response = requests.get(uri, headers=headers, data=body)

    # You want to make sure their email is verified.
    # The user authenticated with Google, authorized your
    # app, and now you've verified their email through Google!
    if userinfo_response.json().get("email_verified"):
        unique_id = userinfo_response.json()["sub"]
        users_email = userinfo_response.json()["email"]
        picture = userinfo_response.json()["picture"]
        users_name = userinfo_response.json()["given_name"]
    else:
        return "User email not available or not verified by Google.", 400

    # Create a user in your db with the information provided
    # by Google
    google_user = User(
        id_=unique_id, name=users_name, email=users_email, profile_pic=picture
    )

    # Doesn't exist? Add it to the database.
    if not User(unique_id).get():
        u = User(unique_id, users_name, users_email, picture)
        u.create()
        return redirect(url_for("page.signup"))

    # Begin user session by logging the user in
    login_user(google_user)

    # Send user back to homepage
    return redirect(url_for("user.home"))


@user.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for("page.index"))

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- <base href="../../static/"> -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    <link href="static/style.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&amp;subset=cyrillic" rel="stylesheet">
    <script src="static/js/app.js"></script>
    <title>Simple FREE URL shortener service</title>
</head>
    <body>
      {% block content %}{% endblock %}
    </body>

</html>

app/templates/default-index-layout.html
{% macro default_index_layout(url_place_holder=None, show_warning=False, show_error=False) %}

        {% if show_error %}
        <div class="alert alert-danger alert-dismissible">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <strong>Not found!</strong> This link was removed or expired
          </div>
        {% endif %}

        <div class="card" id="descTextTop">
            <div class="card-header h2">How to generate a short URL?</div>
            <div class="card-body">
              <p class="card-text">Just put a long and ugly URL into the form and push <strong>Create</strong> button. Your new and short URL will appear just after.</p>
            </div>
        </div>
        <!-- end top text card -->
        <div>
          <p></p>
          <!-- <p>{{ short_url }}</p>
          <p>{{ long_url }}</p> -->
        </div>  
  
        <form action="{{ url_for('page.index') }}" method="post">
          <div class="input-group mb-3" id="longUrl">
            <input type="text" name="longUrlInput" id="longUrlInput" value="" class="form-control" placeholder="{{ url_place_holder }}" >
            <div class="input-group-append">
              <button type="submit" class="btn btn-primary" style="width: 100px;">Create</button>
            </div>
            <!-- end input-group-append -->
          </div>
          <!-- end input-group mb -->
          
        </form>
        <!-- end form long-url -->
        
        {% if show_warning %}
        <div class="alert alert-warning alert-dismissible">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <strong>Error!</strong> Make sure you entered a valid URL
          </div>
        {% endif %}

        <div>
          <p></p>
        </div>  
        <div class="card" id="descTextEnd">
          <div class="card-header h2">Why to use free and fast url shortener?</div>
          <div class="card-body">
            <p class="card-text">Some benefits are on the surface: you can share shorter, nicer links. But also you can manage availability of the links, control a link lifecycle, see statistics of clicks, etc.</p>
          </div>
        </div>
        <!-- end end text card -->
  
{% endmacro %}

app/templates/footer-layout.html
{% macro footer_layout(account=None, status=None) %}

{% endmacro %}

app/templates/layout-header.html
{% macro layout_header(is_authenticated=False, status='free') %}
{%- from "svg_icons.html" import person -%}
{%- from "svg_icons.html" import toggleOff -%}
{%- from "svg_icons.html" import toggleOn -%}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        {% if is_authenticated %}
        <a class="navbar-brand" href="/home"><img src="static/images/rcmnd-logo-transparent.png" alt="Logo"></a>
        {% else %}
        <a class="navbar-brand" href="/"><img src="static/images/rcmnd-logo-transparent.png" alt="Logo"></a>
        {% endif %}
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="d-none d-lg-block h4 font-italic">Share and manage your links!</div>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ml-auto">
            {% if is_authenticated %}
            <li class="nav-item active">
                <a class="nav-link" href="{{url_for('user.urls')}}">My URLs</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{{url_for('user.settings')}}">Settings</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{{url_for('user.logout')}}">
                    <span> {{toggleOff()}}
                      Logout
                    </span>
                </a>
            </li>
            {% else %}
            <li class="nav-item active">
                <a class="nav-link" href="{{url_for('user.login')}}">
                    <span>{{ toggleOn() }}
                    Login
                    </span>
                </a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{{url_for('page.signup')}}">
                    <span>{{ person() }}
                     SignUp
                    </span>
                </a>
            </li>
            {% endif %}
          </ul>
        </div>
        <!-- end collapse -->
    </div>
    <!-- end container -->
</nav>
<!-- end navbar -->
    
{% endmacro %}

app/templates/ready-index-layout.html
{% macro ready_index_layout(long_url=None, short_url=None, url_place_holder=None) %}

<div class="alert alert-success alert-dismissible">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <strong>Success!</strong> You just created a short URL.
</div>

<div id="shortUrl">
    <h6>Your long URL</h6>
    <input type="text" name="longUrlOutput" id="longUrlOutput" value="" class="form-control" placeholder="{{ long_url }}" readonly>
    <p></p>
    <h6>Your short URL</h6>
    
    <div class="input-group mb-3">
        <div id="shortUrlOutput" class="form-control">{{ short_url }}</div>
        <div class="input-group-append">
          <button onclick="copyToClipboard('#shortUrlOutput')" type="submit" class="btn btn-success" style="width: 100px;">Copy</button>
        </div>
        <!-- end input-group-append -->
    </div>
    <!-- end input-group mb-3 -->

    <p></p>
    <div class="btn-group">
        <a href="{{url_for('page.index')}}" class="btn btn-primary" role="button" style="width: 150px;">+ NEW URL</a>
    </div>
    <!-- end div btn-group -->
</div>
<!-- end div shortUrl -->
<p>

</p>
{% endmacro %}

app/templates/svg_icons.html
{%- macro svgIcon(icon_name, width='auto', height='auto', class_name="") -%}
<svg class="{{ icon_name }} {{ class_name }}" width="16" height="16"
     style="min-width: {{ width }}; min-height: {{ height }}">
    <use xlink:href="/static/images/icons-sprite.svg#{{- icon_name -}}"></use>
</svg>
{%- endmacro -%}

{%- macro person() -%}
<svg width="1.2em" height="1.2em" viewBox="0 0 16 16" class="bi bi-person-plus" fill="green" xmlns="http://www.w3.org/2000/svg">
  <path fill-rule="evenodd" d="M8 5a2 2 0 1 1-4 0 2 2 0 0 1 4 0zM6 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm6 5c0 1-1 1-1 1H1s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C9.516 10.68 8.289 10 6 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10zM13.5 5a.5.5 0 0 1 .5.5V7h1.5a.5.5 0 0 1 0 1H14v1.5a.5.5 0 0 1-1 0V8h-1.5a.5.5 0 0 1 0-1H13V5.5a.5.5 0 0 1 .5-.5z"/>
</svg>
{%- endmacro -%}

{%- macro toggleOff() -%}
<svg width="1.2em" height="1.2em" viewBox="0 0 16 16" class="bi bi-toggle2-off" fill="green" xmlns="http://www.w3.org/2000/svg">
  <path d="M9 11c.628-.836 1-1.874 1-3a4.978 4.978 0 0 0-1-3h4a3 3 0 1 1 0 6H9z"/>
  <path fill-rule="evenodd" d="M5 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zm0 1A5 5 0 1 0 5 3a5 5 0 0 0 0 10z"/>
</svg>
{%- endmacro -%}

{%- macro toggleOn() -%}
<svg width="1.2em" height="1.2em" viewBox="0 0 16 16" class="bi bi-toggle2-on" fill="green" xmlns="http://www.w3.org/2000/svg">
  <path d="M7 5H3a3 3 0 0 0 0 6h4a4.995 4.995 0 0 1-.584-1H3a2 2 0 1 1 0-4h3.416c.156-.357.352-.692.584-1z"/>
  <path d="M16 8A5 5 0 1 1 6 8a5 5 0 0 1 10 0z"/>
</svg>
{%- endmacro -%}

app/templates/tables.html
{% macro basic_table(headers=None, data=None, id=None) %}
{% if id and data|length > 0 %}
<div class="table-responsive text-nowrap">
    <table class="table table-sm table-hover table-borderless table-responsive-md table-striped"
           style="display:table" id="{{ id }}">
        {% set header_names = headers.keys() %}
        {% set col_types = headers.values() | list %}

        <thead>
        <tr>
            {% for hd in header_names %}
            <th scope="col">
                {{- hd -}}
            </th>
            {% endfor %}
        </tr>
        </thead>
        <tbody>
        {% for row in data %}
        <tr>
            {% for row_item in row %}
            {% set cur_col_type = col_types[loop.index0] %}
            {% if cur_col_type == 'url' %}
            <td>
                {% set row_text = row_item %}
                {% if row_text|length > 25 %}
                {% set end_offset_text = row_text|length - 15 %}
                {% set row_item_begin = row_item[:15] %}
                {% set row_item_end = row_item[end_offset_text:] %}
                {% set row_text = row_item_begin + '...' + row_item_end %}
                {% endif %}
                <a href="{{ row_item }}" class="card-link ">{{- row_text -}}</a>
            </td>
            {% else %}
            <td> {{- row_item -}}</td>
            {% endif %}
            {% endfor %}
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endif %}
{% endmacro %}

{% macro urls_table(headers=None, data=None, id=None) %}
{% if id and data|length > 0 %}
<form action="{{ url_for('user.urls') }}" method="post">
    <div class="table-responsive text-nowrap">
        <table class="table table-sm table-hover table-borderless table-responsive-md table-striped"
               style="display:table" id="{{id}}">
            {% set header_names = headers.keys() %}
            {% set col_types = headers.values() | list %}

            <thead>
            <tr>
                {% for hd in header_names %}
                <th scope="col">
                    {{- hd -}}
                </th>
                {% endfor %}
            </tr>
            </thead>
            <tbody>
            {% for row in data %}
            <tr>
                <td><input type="checkbox" id="{{ row[0] }}" name="{{ row[0] }}"></td>
                {% for row_item in row %}
                {% set cur_col_type = col_types[loop.index] %}
                {% if cur_col_type == 'url' %}
                <td>
                    {% set row_text = row_item %}
                    {% if row_text|length > 25 %}
                    {% set end_offset_text = row_text|length - 15 %}
                    {% set row_item_begin = row_item[:15] %}
                    {% set row_item_end = row_item[end_offset_text:] %}
                    {% set row_text = row_item_begin + '...' + row_item_end %}
                    {% endif %}
                    <a href="{{ row_item }}" class="card-link ">{{- row_text -}}</a>
                </td>
                {% else %}
                <td> {{- row_item -}}</td>
                {% endif %}
                {% endfor %}
                <!--            <td><a href="{url_for()}" class="card-link">delete</a> </td>-->
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <button type="submit" class="btn btn-outline-secondary">Delete selected</button>
</form>
{% endif %}
{% endmacro %}

app/templates/user_url_forms.html
{% macro new_url_form(show_warning=False) %}
<form action="{{ url_for('user.home') }}" method="post">

    <div id="longUrl">
        <div class="d-flex flex-column">
            <div id="extendUrl" class="collapse">
                <div>
                    <label for="urlDescription">Comment on this URL</label>
                    <input class="form-control" name="urlDescription" id="urlDescription"
                           placeholder="up to 50 symbols">
                </div>
                <p>
                </p>
                <div>
                    <label for="urlDaysLive">Days to live</label>
                    <input class="form-control" type="text" name="urlDaysLive" id="urlDaysLive" placeholder="Always">
                </div>
                <p>
                </p>
                <div>
                    <label for="customSuffix">Custom link</label>
                    <input class="form-control" type="text" name="customSuffix" id="customSuffix">
                </div>
                <p>

                </p>
            </div>
        </div>
        <input type="text" name="longUrlInput" id="longUrlInput" value="" class="form-control"
               placeholder="Enter an URL to shorten">
        <p>

        </p>
        <button type="submit" class="btn btn-primary" style="width: 100px;">Create</button>
        <a href="#extendUrl" class="btn btn-light" data-toggle="collapse" style="width: 100px;">Options</a>

    </div>
</form>
{% if show_warning %}
<div class="alert alert-warning alert-dismissible">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <strong>Error!</strong> Make sure you entered a valid URL
</div>
{% endif %}
{% endmacro %}

{% macro ready_url_form() %}

{% endmacro %}